// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YogaStudio.Infrastructure;

#nullable disable

namespace YogaStudio.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306121242_SeedFakeData")]
    partial class SeedFakeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YogaStudio.Core.Entities.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("BookedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentUserId");

                    b.HasIndex("SessionId", "StudentUserId")
                        .IsUnique();

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("217b96cf-8a42-442c-82f1-9621814531be"),
                            BookedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(4352), new TimeSpan(0, 0, 0, 0, 0)),
                            SessionId = new Guid("39364a0a-8d99-499b-a7cc-9db06b0f05dd"),
                            Status = 0,
                            StudentUserId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("b6828123-de06-4ed5-9cf6-242f07147d39"),
                            BookedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(5354), new TimeSpan(0, 0, 0, 0, 0)),
                            SessionId = new Guid("39364a0a-8d99-499b-a7cc-9db06b0f05dd"),
                            Status = 0,
                            StudentUserId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("177e659f-542d-4a85-8412-48b822b5448f"),
                            BookedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(5360), new TimeSpan(0, 0, 0, 0, 0)),
                            SessionId = new Guid("cb1cc0e5-e01c-45d7-a206-959cd09c8bdd"),
                            Status = 3,
                            StudentUserId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.ClassSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryMode")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("InstructorUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("YogaClassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("RoomId");

                    b.HasIndex("YogaClassId");

                    b.ToTable("ClassSessions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39364a0a-8d99-499b-a7cc-9db06b0f05dd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(250), new TimeSpan(0, 0, 0, 0, 0)),
                            DeliveryMode = 0,
                            DurationMinutes = 60,
                            InstructorUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MaxCapacity = 20,
                            RoomId = new Guid("d3d6d675-ed57-44ce-8fb9-fc5a40acc283"),
                            StartTime = new DateTimeOffset(new DateTime(2026, 3, 8, 6, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(1495), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(251), new TimeSpan(0, 0, 0, 0, 0)),
                            YogaClassId = new Guid("1eddc719-0a8c-422e-b1af-4711f31c27cd")
                        },
                        new
                        {
                            Id = new Guid("cb1cc0e5-e01c-45d7-a206-959cd09c8bdd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(3441), new TimeSpan(0, 0, 0, 0, 0)),
                            DeliveryMode = 0,
                            DurationMinutes = 90,
                            InstructorUserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            MaxCapacity = 10,
                            RoomId = new Guid("cf427c08-a297-4b72-b374-2700c5b346ff"),
                            StartTime = new DateTimeOffset(new DateTime(2026, 3, 8, 22, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(3445), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 151, DateTimeKind.Unspecified).AddTicks(3442), new TimeSpan(0, 0, 0, 0, 0)),
                            YogaClassId = new Guid("7a4c0d7a-eebd-4cae-991e-7b66c84583b2")
                        });
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.InstructorProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("UserId");

                    b.ToTable("InstructorProfiles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Bio = "Expert in Vinyasa and Ashtanga with 10 years of experience.",
                            Specialties = "Vinyasa, Ashtanga"
                        });
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d3d6d675-ed57-44ce-8fb9-fc5a40acc283"),
                            Address = "Piano Terra, Sala 1",
                            Capacity = 20,
                            Name = "Zen Room"
                        },
                        new
                        {
                            Id = new Guid("cf427c08-a297-4b72-b374-2700c5b346ff"),
                            Address = "Primo Piano, Sala 2",
                            Capacity = 10,
                            Name = "Lotus Room"
                        });
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("UserId");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("33333333-3333-3333-3333-333333333333"),
                            EmergencyContact = "Luigi Rossi - 123456789",
                            Notes = "Beginner"
                        },
                        new
                        {
                            UserId = new Guid("44444444-4444-4444-4444-444444444444"),
                            EmergencyContact = "Marco Bianchi - 987654321",
                            Notes = "Intermediate"
                        });
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(8255), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "admin@yogastudio.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(8260), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(9147), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "sarah.connor@yogastudio.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Connor",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(9147), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(9149), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "mario.rossi@example.com",
                            FirstName = "Mario",
                            IsActive = true,
                            LastName = "Rossi",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(9150), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(9166), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "giulia.bianchi@example.com",
                            FirstName = "Giulia",
                            IsActive = true,
                            LastName = "Bianchi",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 149, DateTimeKind.Unspecified).AddTicks(9167), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.YogaClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DifficultyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("YogaClasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1eddc719-0a8c-422e-b1af-4711f31c27cd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 150, DateTimeKind.Unspecified).AddTicks(9146), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Flow dinamico per tonificare corpo e mente.",
                            DifficultyLevel = 1,
                            Name = "Vinyasa Flow",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 150, DateTimeKind.Unspecified).AddTicks(9149), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("7a4c0d7a-eebd-4cae-991e-7b66c84583b2"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 150, DateTimeKind.Unspecified).AddTicks(9885), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Lezione morbida focalizzata su respiro e posture statiche.",
                            DifficultyLevel = 0,
                            Name = "Hatha Yoga Base",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 3, 6, 12, 12, 41, 150, DateTimeKind.Unspecified).AddTicks(9886), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.Booking", b =>
                {
                    b.HasOne("YogaStudio.Core.Entities.ClassSession", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YogaStudio.Core.Entities.User", "StudentUser")
                        .WithMany()
                        .HasForeignKey("StudentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("StudentUser");
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.ClassSession", b =>
                {
                    b.HasOne("YogaStudio.Core.Entities.User", "InstructorUser")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("YogaStudio.Core.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("YogaStudio.Core.Entities.YogaClass", "YogaClass")
                        .WithMany()
                        .HasForeignKey("YogaClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InstructorUser");

                    b.Navigation("Room");

                    b.Navigation("YogaClass");
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.InstructorProfile", b =>
                {
                    b.HasOne("YogaStudio.Core.Entities.User", "User")
                        .WithOne("InstructorProfile")
                        .HasForeignKey("YogaStudio.Core.Entities.InstructorProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.StudentProfile", b =>
                {
                    b.HasOne("YogaStudio.Core.Entities.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("YogaStudio.Core.Entities.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("YogaStudio.Core.Entities.User", b =>
                {
                    b.Navigation("InstructorProfile");

                    b.Navigation("StudentProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
